.TH iCON metrics 1 
.SH NAME
icon-metrics \- NGBS iCON smart home control system metrics reader
.SH SYNOPSIS
.B icon-metrics
.B icon-metrics --config /etc/icon-metrics/config.yml
.SH DESCRIPTION
.B icon-metrics
reads data from NGBS iCON smart home control systems.
It exposes metrics to be read by prometheus.
.SH AUTHORS
.B icon-metrics
was written by 
Ármin Csutorás <csutorasa@gmail.com>
.PP
This document was written by Ármin Csutorás <csutorasa@gmail.com> for Debian.
