{
 "title": "iCON controllers",
 "description": "Details of the controllers.",
 "tags": [ "iCON" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sysId",
    "label": "Controller ID",
    "query": {
     "query": "label_values(icon_controller_connected,sysId)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Controllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Connected controllers",
   "type": "stat",
   "description": "Connection status for all controllers to be monitored.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_controller_connected{sysId=~\"$sysId\"}",
     "legendFormat": "{{sysId}}"
    }
   ]
  },
  {
   "title": "Connected rooms",
   "type": "stat",
   "description": "Number of connected rooms by controllers.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rooms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (sysId) (icon_room_connected{sysId=~\"$sysId\"} > 0)",
     "legendFormat": "{{sysId}}"
    }
   ]
  },
  { "title": "HTTP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP response time",
   "type": "timeseries",
   "description": "Average HTTP response time by controller, endpoint and status codes.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(sysId, name, response) (increase(icon_http_client_seconds_sum{sysId=~\"$sysId\"}[2m])) / sum by(sysId, name, response) (increase(icon_http_client_seconds_count{sysId=~\"$sysId\"}[2m]))",
     "legendFormat": "{{sysId}} {{name}} {{response}}"
    }
   ]
  },
  {
   "title": "HTTP RPM",
   "type": "timeseries",
   "description": "Number of requests by controller and endpoint.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by (name, sysId) (increase(icon_http_client_seconds_count{sysId=~\"$sysId\"}[1m]))",
     "legendFormat": "{{sysId}} {{name}}"
    }
   ]
  }
 ]
}