{
 "title": "iCON metrics system",
 "description": "Details of the iCON metrics application",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU seconds ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "uptime", "legendFormat": "__auto" }
   ]
  },
  { "title": "HTTP API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "HTTP response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(sysId, name, response) (increase(icon_http_client_seconds_sum[2m])) / sum by(sysId, name, response) (increase(icon_http_client_seconds_count[2m]))",
     "legendFormat": "{{sysId}} {{name}} {{response}}"
    }
   ]
  },
  {
   "title": "HTTP RPM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by (name, sysId) (increase(icon_http_client_seconds_count[1m]))",
     "legendFormat": "{{sysId}} {{name}}"
    }
   ]
  }
 ]
}