{
 "title": "iCON rooms",
 "description": "Details of the rooms.",
 "tags": [ "iCON" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sysId",
    "label": "Controller ID",
    "query": {
     "query": "label_values(icon_controller_connected, sysId)"
    }
   },
   {
    "name": "room",
    "label": "Room name",
    "query": {
     "query": "label_values(icon_relay_on{sysId=\"$sysId\"}, room)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Controller $sysId", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "sysId" },
  {
   "title": "Controller connected",
   "type": "stat",
   "description": "If the controller is connected.",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "icon_controller_connected{sysId=~\"$sysId\"}",
     "legendFormat": "{{sysId}}"
    }
   ]
  },
  {
   "title": "Heating or cooling",
   "type": "stat",
   "description": "If the controller is set to heating or cooling mode.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "icon_heating{sysId=~\"$sysId\"}",
     "legendFormat": "{{sysId}}"
    }
   ]
  },
  {
   "title": "Eco or comfort",
   "type": "stat",
   "description": "If the controller is set to economy or comfort mode.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "icon_eco{sysId=~\"$sysId\"}",
     "legendFormat": "{{sysId}}"
    }
   ]
  },
  {
   "title": "External temperature",
   "type": "stat",
   "description": "External temperature measured by the controller.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_external_temperature{sysId=\"$sysId\"}"
    }
   ]
  },
  {
   "title": "Water temperature",
   "type": "stat",
   "description": "Heating or cooling water temperature.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "icon_water_temperature{sysId=~\"$sysId\"}",
     "legendFormat": "{{sysId}}"
    }
   ]
  },
  {
   "title": "Connected rooms",
   "type": "stat",
   "description": "Number of connected rooms.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "rooms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (sysId) (icon_room_connected{sysId=~\"$sysId\"} > 0)",
     "legendFormat": "{{sysId}}"
    }
   ]
  },
  { "title": "Room $room", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "room" },
  {
   "title": "Room connected",
   "type": "stat",
   "description": "If the room is connected.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "icon_room_connected{sysId=~\"$sysId\",room=~\"$room\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Current room temperature.",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "icon_temperature{sysId=~\"$sysId\",room=~\"$room\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Temperature to target",
   "type": "gauge",
   "description": "Difference between the current room temperature and the target temperature.",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "icon_temperature{sysId=~\"$sysId\",room=~\"$room\"} - icon_target_temperature{sysId=~\"$sysId\",room=~\"$room\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "External to temperature",
   "type": "gauge",
   "description": "Difference between the external temperature and the current room temperature.",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sysId) (icon_external_temperature{sysId=~\"$sysId\"}) - sum by (sysId) (icon_temperature{sysId=~\"$sysId\",room=~\"$room\"})",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Water to temperature",
   "type": "gauge",
   "description": "Difference between the water temperature and current room temperature.",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (sysId) (icon_water_temperature{sysId=~\"$sysId\"}) - sum by (sysId) (icon_temperature{sysId=~\"$sysId\",room=~\"$room\"})",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "description": "Relative humidity of the room.",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "icon_humidity{sysId=~\"$sysId\",room=~\"$room\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Relay",
   "type": "stat",
   "description": "If the relay is open.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "icon_relay_on{sysId=~\"$sysId\",room=~\"$room\"}",
     "legendFormat": "{{room}}"
    }
   ]
  }
 ]
}