{
 "title": "iCON thermostat",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sysId",
    "query": {
     "query": "label_values(icon_controller_connected, sysId)"
    }
   },
   {
    "name": "room",
    "query": {
     "query": "label_values(icon_relay_on{sysId=\"$sysId\"}, room)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_temperature{sysId=~\"$sysId\",room=~\"$room\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Relay",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_relay_on{sysId=~\"$sysId\",room=~\"$room\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Temperature to target",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_temperature{sysId=~\"$sysId\",room=~\"$room\"} - icon_target_temperature{sysId=~\"$sysId\",room=~\"$room\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_humidity{sysId=~\"$sysId\",room=~\"$room\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Temperature above dew",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_temperature{sysId=~\"$sysId\",room=~\"$room\"} - icon_dew_temperature{sysId=~\"$sysId\",room=~\"$room\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Water temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_water_temperature{sysId=\"$sysId\"}"
    }
   ]
  },
  {
   "title": "External temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_external_temperature{sysId=\"$sysId\"}"
    }
   ]
  },
  {
   "title": "Controller connected",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_controller_connected{sysId=~\"$sysId\"}",
     "legendFormat": "{{sysId}}"
    }
   ]
  },
  {
   "title": "Room connected",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "icon_room_connected{sysId=~\"$sysId\",room=~\"$room\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "HTTP response time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "increase(icon_http_client_seconds_sum{response!='0',sysId=\"$sysId\"}[2m]) / increase(icon_http_client_seconds_count{response!='0',sysId=\"$sysId\"}[2m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}