#!/usr/bin/env bash

if [ $(id -u) -ne 0 ]
  then echo Please run this script as root or using sudo!
  exit
fi

OUTPUT=

# Make sure directory is correct
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR

# Application
mkdir -p $OUTPUT/usr/local/bin/
cp ../icon-metrics $OUTPUT/usr/local/bin/icon-metrics
mkdir -p $OUTPUT/etc/icon-metrics/
cp ../config.yml $OUTPUT/etc/icon-metrics/config.yml

# Debian
mkdir -p $OUTPUT/DEBIAN
cp debian/changelog $OUTPUT/DEBIAN/
cp debian/conffiles $OUTPUT/DEBIAN/
cp debian/control $OUTPUT/DEBIAN/
sed -i "s/Architecture:.*/Architecture: $ARCH/g" $OUTPUT/DEBIAN/control

# Systemd
mkdir -p $OUTPUT/etc/systemd/system/
cp systemd/icon-metrics.service $OUTPUT/etc/systemd/system/icon-metrics.service

# Bash completion
mkdir -p $OUTPUT/usr/share/bash-completion/completions/
cp bash/bash-completion $OUTPUT/usr/share/bash-completion/completions/icon-metrics

# Documentation
mkdir -p $OUTPUT/usr/share/doc/icon-metrics/
cp ../LICENSE $OUTPUT/usr/share/doc/icon-metrics/copyright
cp debian/changelog $OUTPUT/usr/share/doc/icon-metrics/changelog.Debian
gzip --best -n -f $OUTPUT/usr/share/doc/icon-metrics/changelog.Debian
mkdir -p $OUTPUT/usr/share/man/man1/
cp man/icon-metrics.1 $OUTPUT/usr/share/man/man1/icon-metrics.1
gzip --best -n -f $OUTPUT/usr/share/man/man1/icon-metrics.1
