name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
        
      - name: Build
        run: go build
        env:
          GOOS: windows
          GOARCH: amd64
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: icon-metrics-windows-amd64
          path: |
            icon-metrics.exe
            config.yml
        
      - name: Build
        run: go build
        env:
          GOOS: linux
          GOARCH: amd64
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: icon-metrics-linux-amd64
          path: |
            icon-metrics
            config.yml
        
      - name: Build
        run: go build
        env:
          GOOS: linux
          GOARCH: arm64
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: icon-metrics-linux-arm64
          path: |
            icon-metrics
            config.yml
        
      - name: Build
        run: go build
        env:
          GOOS: darwin
          GOARCH: amd64
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: icon-metrics-darwin-amd64
          path: |
            icon-metrics
            config.yml
        
      - name: Build
        run: go build
        env:
          GOOS: darwin
          GOARCH: arm64
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: icon-metrics-darwin-arm64
          path: |
            icon-metrics
            config.yml

      