name: Build
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_windows:
    name: Build windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
        
      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: windows
          GOARCH: amd64
      
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: icon-metrics-windows-amd64
          path: |
            icon-metrics.exe
            config.yml

      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: windows
          GOARCH: arm64
      
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: icon-metrics-windows-arm64
          path: |
            icon-metrics.exe
            config.yml

  build_linux:
    name: Build linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Create deb
        run: packaging/pkg-deb amd64 1.3.1
      
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: icon-metrics-deb-amd64
          path: packaging/icon-metrics-amd64-1.3.1-deb
      
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: icon-metrics-linux-amd64
          path: |
            icon-metrics
            config.yml
        
      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: linux
          GOARCH: arm64

      - name: Create deb
        run: packaging/pkg-deb arm64 1.3.1
      
      - name: Upload deb
        uses: actions/upload-artifact@v4
        with:
          name: icon-metrics-deb-arm64
          path: packaging/icon-metrics-arm64-1.3.1-deb
      
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: icon-metrics-linux-arm64
          path: |
            icon-metrics
            config.yml
        
  build_darwin:
    name: Build Mac
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: darwin
          GOARCH: amd64
      
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: icon-metrics-darwin-amd64
          path: |
            icon-metrics
            config.yml
        
      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: darwin
          GOARCH: arm64
      
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: icon-metrics-darwin-arm64
          path: |
            icon-metrics
            config.yml
