name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
        
      - name: Build
        run: go build
        env:
          GOARCH: ${{ matrix.arch }}
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: icon-metrics
          path: |
            icon-metrics
            icon-metrics.exe
            config.yml

      