name: Build
on:
  push:
    branches:
      - master

jobs:
  build_windows:
    name: Build windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        
      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: windows
          GOARCH: amd64
      
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: icon-metrics-windows-amd64
          path: |
            icon-metrics.exe
            config.yml

  build_linux:
    name: Build linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Prepare deb
        run: .deb/prepare.sh

      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Create deb
        run: .deb/build.sh amd64
      
      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: icon-metrics-deb-amd64
          path: .deb/icon-metrics.deb
      
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: icon-metrics-linux-amd64
          path: |
            icon-metrics
            config.yml
        
      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: linux
          GOARCH: arm64

      - name: Create deb
        run: .deb/build.sh arm64
      
      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: icon-metrics-deb-arm64
          path: .deb/icon-metrics.deb
      
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: icon-metrics-linux-arm64
          path: |
            icon-metrics
            config.yml
        
  build_darwin:
    name: Build Mac
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: darwin
          GOARCH: amd64
      
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: icon-metrics-darwin-amd64
          path: |
            icon-metrics
            config.yml
        
      - name: Build
        run: go build -ldflags "-s -w"
        env:
          GOOS: darwin
          GOARCH: arm64
      
      - name: Upload output
        uses: actions/upload-artifact@v3
        with:
          name: icon-metrics-darwin-arm64
          path: |
            icon-metrics
            config.yml

      
