name: Build
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
        
      - name: Build
        run: go build
      
      - name: Create package
        uses: actions/upload-artifact@v2
        with:
          name: XOutput
          path: |
          icon-metrics
          icon-metrics.exe
          config.yml

      